import { useState } from 'react'
import { AlertTriangle, ArrowRight, Check, CheckCircle2, ChevronDown, ChevronUp, Coins, Lock, Network, RefreshCw, Star, Wallet, Zap } from 'lucide-react'
import { ProgressionLineChart } from '../../components/charts/InstitutionalCharts'
import FreedomPlusOrbit from './FreedomPlusOrbit'
import '../ActivationCenter/ActivationCenterPage.css'

import { tokenUnits } from '../../Services/freedomPlus'
import { hasTokenBalance } from '../../utils/walletReads.js'

function LevelPreview({ config, filled = 0, locked }) {
  const rings = config.orbit === 'P39' ? [3, 9, 27] : config.orbit === 'P14' ? [2, 4, 8] : config.orbit === 'P12' ? [3, 9] : config.orbit === 'P6' ? [2, 4] : config.orbit === 'P4' ? [4] : [3]
  const center = 110
  let position = 0
  const nodes = rings.flatMap((count, ringIndex) => Array.from({ length: count }, (_, index) => {
    position += 1
    const radius = 42 + ringIndex * 31
    const angle = (Math.PI * 2 * index) / count - Math.PI / 2
    return { position, ring: ringIndex + 1, x: center + Math.cos(angle) * radius, y: center + Math.sin(angle) * radius }
  }))
  return <div className={`level-orbit-preview level-orbit-preview--${config.orbit.toLowerCase()} ${filled ? 'has-current-cycle-fills' : 'is-empty-cycle'}`}>
    <div className="level-orbit-preview__stage" aria-hidden="true"><svg className="level-orbit-preview__svg" viewBox="0 0 220 220">
      {rings.map((_, index) => <circle key={index} className={`level-orbit-preview__svg-ring line-${index + 1}`} cx={center} cy={center} r={42 + index * 31} />)}
      <g className="level-orbit-preview__nodes">{nodes.map((node) => <circle key={node.position} className={`level-orbit-preview__svg-node line-${node.ring} ${node.position <= filled ? 'is-filled' : 'is-neutral'} ${locked ? 'is-locked' : ''}`} cx={node.x} cy={node.y} r={node.ring === 3 ? 4 : 6} />)}</g>
      <circle className="level-orbit-preview__core" cx={center} cy={center} r="18" /><text className="level-orbit-preview__core-label" x={center} y={center + 4} textAnchor="middle">{config.orbit}</text>
    </svg></div>
    <div className="level-orbit-preview__meta"><strong>{config.positions} positions</strong><span>{config.rings}</span></div>
  </div>
}

export default function FreedomPlusActivationCenter({ account, isConnected, connect, data, loading, networkReady, networkName, levels, activeLevels, progressionData, activationSummary, nextLevel, sponsor, sponsorCode, referralId, busy, gateway, onRegister, onActivate, onViewOrbit, selectedLevel, setSelectedLevel, cycle, setCycle, loadOrbit, visualOrbit, selectedConfig, selectedPosition, setSelectedPosition, formatToken, short }) {
  const [openDetails, setOpenDetails] = useState({})
  const registered = Boolean(data?.chain?.registered)

  if (!isConnected) return <div className="activation-page"><div className="activation-hero"><div className="activation-hero__content"><div className="activation-hero__eyebrow glass-panel"><span className="activation-hero__eyebrow-dot" /><span className="activation-hero__eyebrow-text">Wallet-first protocol access</span></div><div className="activation-hero__text-block"><h1 className="activation-hero__title">Freedom-Plus Activation Center</h1><p className="activation-hero__description soft-text">Connect your wallet to register, activate levels, review balances and inspect every Freedom-Plus orbit.</p><button type="button" className="activate-btn" onClick={connect}><Wallet /> Connect wallet</button></div></div><div className="activation-hero__visual glass-panel"><div className="activation-hero__visual-header"><span className="activation-hero__visual-title">Status</span><span className="activation-hero__visual-status">Disconnected</span></div><div className="activation-hero__visual-box"><Lock /></div></div></div></div>
  if (loading && !data) return <div className="activation-page"><div className="activation-hero__text-block activation-hero__text-block--loading"><RefreshCw className="spin" /><h1>Loading activation state</h1><p>Confirming registration, balances, levels and orbit cycles.</p></div></div>

  if (!data) return <div className="activation-page" role="status"><AlertTriangle /><h1>Account status unavailable</h1><p>Refresh to retry loading your Freedom-Plus levels.</p></div>

  return <div className="activation-page freedom-plus-activation-page">
    {!networkReady && <div className="activation-inline-notice activation-inline-notice--warning"><AlertTriangle /><div><strong>Switch to {networkName}</strong><span>Registration and activation remain unavailable until the configured network is selected.</span></div></div>}
    <div className="activation-hero">
      <div className="activation-hero__content"><div className="activation-hero__eyebrow glass-panel"><span className="activation-hero__eyebrow-dot" /><span className="activation-hero__eyebrow-text">Registration, readiness, and manual level progression</span></div><div className="activation-hero__text-block"><h1 className="activation-hero__title">Freedom-Plus</h1><p className="activation-hero__description soft-text">Track your Freedom-Plus progression, inspect live orbit readiness, and activate the next eligible level from one guided flow.</p></div><div className="activation-hero__chips"><span className="activation-hero__chip glass-panel">Wallet Connected</span><span className={`activation-hero__chip glass-panel ${registered ? '' : 'inactive'}`}>{registered ? 'Freedom-Plus active' : 'Freedom-Plus Level 1 not active'}</span><span className="activation-hero__chip glass-panel">Highest Level: {activeLevels.size}</span><span className="activation-hero__chip glass-panel">Manual upgrades only</span></div></div>
      <div className="activation-hero__visual glass-panel"><div className="activation-hero__visual-header"><span className="activation-hero__visual-title">Level Progression</span><span className="activation-hero__visual-status">{activeLevels.size}/7 Activated</span></div><div className="line-chart-container line-chart-container--institutional"><ProgressionLineChart data={progressionData} valueKey="cumulative" activeKey="activated" labelKey="level" maxValue={7} ariaLabel="Freedom-Plus level activation progression chart" /></div><p className="activation-hero__visual-note muted-text">{nextLevel ? `Level ${nextLevel} is next. Each level is activated manually and sequentially.` : 'All seven Freedom-Plus levels are active.'}</p><div className="activation-referral-card"><span>FFN identity</span><strong>{referralId || short(account)}</strong><small>Permanent sponsor: {sponsorCode || short(sponsor)}</small></div></div>
    </div>

    <section className="activation-levels glass-panel activation-levels--fullwidth"><div className="activation-section-heading"><span className="activation-section-heading__eyebrow muted-text">7 Premium Levels</span></div><div className="activation-levels__grid">
      {levels.map((config) => { const active = activeLevels.has(config.level); const gatewayReady = Boolean(gateway?.registered && gateway?.levelOneActive); const ready = !active && (config.level === 1 ? (!registered && gatewayReady) : (registered && activeLevels.has(config.level - 1))); const locked = !active && !ready; const summary = activationSummary?.orbitSummaries?.find((entry) => Number(entry.level) === config.level); const filled = Number(summary?.filledPositions || 0); const open = Boolean(openDetails[config.level]); const hasBalance = hasTokenBalance(data?.chain?.usdtRaw, tokenUnits(config.price)); return <div key={config.level} className={`activation-levels__card premium-card compact-level-card ${active ? 'activated' : ''} ${ready ? 'next' : ''} ${locked ? 'is-locked-level' : ''}`}>
        {locked && <div className="activation-level-locked-glass" aria-hidden="true"><Lock /></div>}
        <div className="activation-level-info-grid"><div className="activation-level-info-cell"><span>Level</span><strong>{config.level}</strong></div><div className="activation-level-info-cell activation-level-info-cell--right"><span>Stage</span><strong className="activation-level-stage">{config.level === 2 && <Zap size={14} aria-hidden="true" />}{config.level === 6 && <Star size={14} aria-hidden="true" />}{config.stage}</strong></div><div className="activation-level-info-cell"><span>Payout Engine</span><strong>{config.orbit} Orbit</strong></div><div className="activation-level-info-cell activation-level-info-cell--right"><span>Status</span><strong className={`activation-level-status-inline ${active ? 'is-active' : ready ? 'is-ready' : 'is-locked'}`}>{active ? <CheckCircle2 /> : ready ? <Coins /> : <Lock />}{active ? 'Activated' : ready ? 'Ready to Activate' : 'Locked'}</strong></div><div className="activation-level-info-cell"><span>Price</span><strong>Level Price</strong></div><div className="activation-level-info-cell activation-level-info-cell--right"><span>Activation Amount</span><strong className={`activation-level-price-token ${hasBalance ? 'is-sufficient' : 'is-insufficient'}`}><i aria-hidden="true">T</i>{config.price.toLocaleString()} USDT</strong></div></div>
        <LevelPreview config={config} filled={filled} locked={locked} />
        <div className="compact-level-card__actions"><button type="button" className="view-orbit-btn compact-action-btn" onClick={() => onViewOrbit(config.level)}>View Orbit <ArrowRight /></button>{active ? <span className="activate-btn compact-action-btn"><Check /> Activated</span> : <button type="button" className={ready ? 'activate-btn compact-action-btn' : 'locked-btn compact-action-btn'} disabled={!ready || loading || Boolean(busy) || !networkReady} onClick={() => config.level === 1 && !registered ? onRegister() : onActivate(config)}>{busy === `level-${config.level}` || (config.level === 1 && busy === 'register') ? 'Activating...' : ready ? 'Activate' : 'Locked'}</button>}</div>
        <button type="button" className="compact-level-card__toggle" onClick={() => setOpenDetails((current) => ({ ...current, [config.level]: !open }))} aria-expanded={open}><span>{open ? 'Hide Details' : 'Show Details'}</span>{open ? <ChevronUp /> : <ChevronDown />}</button>
        {open && <div className="compact-level-card__dropdown"><div className="level-metrics"><div className="metric-item"><span className="metric-label">Current Cycle</span><span className="metric-value">{active ? summary?.currentCycle || 1 : '-'}</span></div><div className="metric-item"><span className="metric-label">Positions Filled</span><span className="metric-value">{filled} / {config.positions}</span></div><div className="metric-item"><span className="metric-label">First Activation Reward</span><span className="metric-value">{config.price.toLocaleString()} FPT</span></div><div className="metric-item"><span className="metric-label">Recycle Reward</span><span className="metric-value">{(config.price / 2).toLocaleString()} FPTr</span></div></div><p className="muted-text">{config.payouts}. No automatic level upgrade or escrow is used in Freedom-Plus.</p></div>}
      </div> })}
    </div></section>

    {!registered && !(gateway?.registered && gateway?.levelOneActive) && <div className="activation-inline-notice activation-inline-notice--warning"><AlertTriangle /><div><strong>F-Freedom Level 1 required</strong><span>Activate F-Freedom Level 1 before joining Freedom-Plus.</span></div></div>}

    {registered && <section className="activation-main-grid"><div className="activation-main-grid__left"><div className="glass-panel"><div className="activation-section-heading"><span className="activation-section-heading__eyebrow muted-text">Live level structure</span><h2>Orbit Position and Cycle</h2></div><div className="fp-toolbar"><label>Level<select value={selectedLevel} onChange={(event) => { setSelectedLevel(Number(event.target.value)); setSelectedPosition(null) }}>{levels.map((item) => <option key={item.level} value={item.level} disabled={!activeLevels.has(item.level)}>Level {item.level} / {item.orbit}</option>)}</select></label><label>Cycle<input type="number" min="1" value={cycle} placeholder="Current" onChange={(event) => { setCycle(event.target.value); setSelectedPosition(null) }} /></label><button type="button" onClick={loadOrbit}><RefreshCw /> Refresh</button></div><FreedomPlusOrbit orbitType={selectedConfig?.orbit} positions={visualOrbit} owner={account} onSelect={setSelectedPosition} /></div></div><aside className="activation-main-grid__right"><div className="glass-panel activation-help-card">{selectedPosition ? <><span>Position {selectedPosition.position}</span><h3>{selectedPosition.financial ? 'Payment-linked placement' : 'Structural placement'}</h3><dl><div><dt>Participant</dt><dd>{short(selectedPosition.participant)}</dd></div><div><dt>Matrix parent</dt><dd>{short(selectedPosition.structuralParent)}</dd></div><div><dt>Ring</dt><dd>{selectedPosition.ring || selectedPosition.line}</dd></div><div><dt>Cycle</dt><dd>{selectedPosition.cycle}</dd></div><div><dt>Amount</dt><dd>{formatToken(selectedPosition.amount)} USDT</dd></div></dl></> : <><Network /><h3>Select a filled position</h3><p>Inspect its participant, structural parent, ring, cycle and recorded amount.</p></>}</div></aside></section>}
  </div>
}
