import { useEffect, useState } from 'react'
import { Activity, Archive, Check, Eye, ImagePlus, MessageCircle, Plus, RefreshCw, Save, ShieldCheck, Trophy, X } from 'lucide-react'
import './AdminTasksManager.css'

const EMPTY={title:'',summary:'',instructions:'',actionUrl:'',rewardLabel:'',proofRequirements:'',startsAt:'',endsAt:'',status:'draft',imageId:'',imageUrl:'',notifyUsers:false}
export default function AdminTasksManager({adminApi,toast}){
 const [view,setView]=useState('tasks'),[tasks,setTasks]=useState([]),[submissions,setSubmissions]=useState([]),[comments,setComments]=useState([]),[rewards,setRewards]=useState([]),[form,setForm]=useState(EMPTY),[editing,setEditing]=useState(''),[busy,setBusy]=useState(false)
 const load=async()=>{setBusy(true);try{const [a,b,c,d]=await Promise.all([adminApi('/api/admin/tasks'),adminApi('/api/admin/tasks/submissions/list'),adminApi('/api/admin/tasks/comments/list'),adminApi('/api/admin/tasks/rewards/list')]);setTasks(a.data||[]);setSubmissions(b.data||[]);setComments(c.data||[]);setRewards(d.data||[])}catch(e){toast.danger(e.message)}finally{setBusy(false)}}
 useEffect(()=>{load()},[])
 const update=(k,v)=>setForm(s=>({...s,[k]:v}))
 const reset=()=>{setForm(EMPTY);setEditing('')}
 const edit=t=>{setEditing(t._id);setForm({...EMPTY,...t,startsAt:t.startsAt?new Date(t.startsAt).toISOString().slice(0,16):'',endsAt:t.endsAt?new Date(t.endsAt).toISOString().slice(0,16):'',notifyUsers:false});window.scrollTo({top:0,behavior:'smooth'})}
 const upload=async file=>{if(!file)return;try{const data=await adminApi('/api/admin/notifications/media',{method:'POST',headers:{'Content-Type':file.type,'X-File-Name':file.name},body:file});update('imageId',data.image?.id||'');update('imageUrl',data.image?.url||'');toast.success('Task image uploaded.')}catch(e){toast.danger(e.message)}}
 const save=async()=>{setBusy(true);try{await adminApi(editing?`/api/admin/tasks/${editing}`:'/api/admin/tasks',{method:editing?'PATCH':'POST',body:JSON.stringify(form)});toast.success(editing?'Task updated.':'Task created.');reset();await load()}catch(e){toast.danger(e.message)}finally{setBusy(false)}}
 const review=async(id,status)=>{const reviewNote=window.prompt(status==='approved'?'Optional approval note':'Rejection feedback is recommended','')??null;if(reviewNote===null)return;try{const r=await adminApi(`/api/admin/tasks/submissions/${id}`,{method:'PATCH',body:JSON.stringify({status,reviewNote})});toast.success(`Submission ${status}.`);if(r.data?.notification?.warning)toast.warning(r.data.notification.warning);await load()}catch(e){toast.danger(e.message)}}
 const moderate=async id=>{if(!window.confirm('Remove this comment from the public discussion?'))return;try{await adminApi(`/api/admin/tasks/comments/${id}`,{method:'DELETE',body:JSON.stringify({})});toast.success('Comment removed.');await load()}catch(e){toast.danger(e.message)}}
 const proof=async id=>{try{const blob=await adminApi(`/api/admin/tasks/media/${id}`,{responseType:'blob'});const url=URL.createObjectURL(blob);window.open(url,'_blank','noopener,noreferrer');setTimeout(()=>URL.revokeObjectURL(url),60000)}catch(e){toast.danger(e.message)}}
 const reward=async row=>{const status=window.prompt('Reward status: pending, earned, issued, failed, cancelled',row.status);if(!status)return;const transactionHash=status==='issued'?window.prompt('Transaction hash (leave blank for an off-chain reward)','')||'':'';try{await adminApi(`/api/admin/tasks/rewards/${row._id}`,{method:'PATCH',body:JSON.stringify({status,transactionHash})});toast.success('Reward ledger updated.');await load()}catch(e){toast.danger(e.message)}}
 return <section className="admin-tasks"><header><div><Activity size={21}/><span><h2>Community Tasks</h2><p>Publishing, proof review, discussion moderation, and rewards.</p></span></div><button onClick={load} disabled={busy}><RefreshCw size={16}/>Refresh</button></header><nav>{[['tasks','Tasks'],['submissions','Submissions'],['comments','Moderation'],['rewards','Rewards']].map(([id,label])=><button key={id} className={view===id?'active':''} onClick={()=>setView(id)}>{label}</button>)}</nav>
 {view==='tasks'?<><div className="admin-task-form"><h3>{editing?'Edit task':'Create task'}</h3><div className="admin-task-grid"><label>Title<input value={form.title} onChange={e=>update('title',e.target.value)}/></label><label>Reward label<input value={form.rewardLabel} onChange={e=>update('rewardLabel',e.target.value)}/></label><label className="wide">Summary<textarea rows="2" value={form.summary} onChange={e=>update('summary',e.target.value)}/></label><label className="wide">Instructions<textarea rows="5" value={form.instructions} onChange={e=>update('instructions',e.target.value)}/></label><label>Action URL<input type="url" value={form.actionUrl} onChange={e=>update('actionUrl',e.target.value)}/></label><label>Proof requirements<input value={form.proofRequirements} onChange={e=>update('proofRequirements',e.target.value)}/></label><label>Starts<input type="datetime-local" value={form.startsAt} onChange={e=>update('startsAt',e.target.value)}/></label><label>Ends<input type="datetime-local" value={form.endsAt} onChange={e=>update('endsAt',e.target.value)}/></label><label>Status<select value={form.status} onChange={e=>update('status',e.target.value)}><option value="draft">Draft</option><option value="published">Published</option><option value="closed">Closed</option><option value="archived">Archived</option></select></label><label className="upload"><ImagePlus size={16}/>{form.imageId?'Replace image':'Add task image'}<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>upload(e.target.files?.[0])}/></label><label className="check"><input type="checkbox" checked={form.notifyUsers} onChange={e=>update('notifyUsers',e.target.checked)}/>Notify registered users when publishing</label></div><div className="admin-task-actions"><button onClick={save} disabled={busy||!form.title||!form.summary||!form.instructions}>{editing?<Save size={15}/>:<Plus size={15}/>} {editing?'Save changes':'Create task'}</button>{editing?<button onClick={reset}><X size={15}/>Cancel</button>:null}</div></div><div className="admin-task-list">{tasks.map(t=><article key={t._id}>{t.imageUrl?<img src={t.imageUrl} alt=""/>:null}<div><span>{t.state}</span><h3>{t.title}</h3><p>{t.summary}</p><small>{t.participantCount||0} joined · {t.submissionCount||0} submissions · {t.commentCount||0} comments</small></div><button onClick={()=>edit(t)}>Edit</button><button onClick={()=>adminApi(`/api/admin/tasks/${t._id}`,{method:'DELETE'}).then(load)} title="Archive"><Archive size={15}/></button></article>)}</div></> : null}
 {view==='submissions'?<div className="admin-task-table">{submissions.map(s=><article key={s._id}><div><span>{s.status}</span><h3>{s.taskId?.title}</h3><p>{s.walletAddress}</p>{s.proofText?<p>{s.proofText}</p>:null}{s.proofUrl?<a href={s.proofUrl} target="_blank" rel="noreferrer">Open proof link</a>:null}</div><div>{s.proofImageId?<button onClick={()=>proof(s.proofImageId)}><Eye size={15}/>Proof image</button>:null}<button onClick={()=>review(s._id,'approved')}><Check size={15}/>Approve</button><button onClick={()=>review(s._id,'rejected')}><X size={15}/>Reject</button></div></article>)}</div>:null}
 {view==='comments'?<div className="admin-task-table">{comments.map(c=><article key={c._id}><MessageCircle size={18}/><div><h3>{c.walletAddress}</h3><p>{c.isRemoved?'Removed comment':c.body}</p></div>{!c.isRemoved?<button onClick={()=>moderate(c._id)}>Remove</button>:<ShieldCheck size={17}/>}</article>)}</div>:null}
 {view==='rewards'?<div className="admin-task-table">{rewards.map(r=><article key={r._id}><Trophy size={18}/><div><span>{r.status}</span><h3>{r.taskId?.title}</h3><p>{r.walletAddress} · {r.rewardLabel||'No reward label'}</p>{r.transactionHash?<small>{r.transactionHash}</small>:null}</div><button onClick={()=>reward(r)}>Update</button></article>)}</div>:null}
 </section>
}
